# Copyright (C) 2018 Sebastian Pipping <sebastian@pipping.org>
# Licensed under the MIT license

language: cpp
dist: trusty

addons:
  apt:
    packages:
      - cmake-data
      - cmake
      - doxygen
      - graphviz
      - libcpptest-dev

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --config Release
